2019-03-06 17:27:08,681-selenium.webdriver.remote.remote_connection-INFO-Could not connect to port 4723 on host 127.0.0.1
2019-03-06 17:27:08,681-selenium.webdriver.remote.remote_connection-INFO-Could not connect to port 4723 on host 127.0.0.1
2019-03-06 17:27:08,681-selenium.webdriver.remote.remote_connection-INFO-Could not get IP address for host: 127.0.0.1
2019-03-06 17:27:08,681-selenium.webdriver.remote.remote_connection-INFO-Could not get IP address for host: 127.0.0.1
2019-03-06 17:27:09,683-urllib3.connectionpool-WARNING-Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024017DFCF28>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2019-03-06 17:27:09,683-urllib3.connectionpool-WARNING-Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024017DFCF28>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2019-03-06 17:27:11,533-urllib3.connectionpool-WARNING-Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024017E1F0B8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2019-03-06 17:27:11,533-urllib3.connectionpool-WARNING-Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024017E1F0B8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2019-03-06 17:27:12,535-urllib3.connectionpool-WARNING-Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024017E1F1D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2019-03-06 17:27:12,535-urllib3.connectionpool-WARNING-Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024017E1F1D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2019-03-06 17:27:42,259-selenium.webdriver.remote.remote_connection-INFO-Could not connect to port 4723 on host 127.0.0.1
2019-03-06 17:27:42,259-selenium.webdriver.remote.remote_connection-INFO-Could not connect to port 4723 on host 127.0.0.1
2019-03-06 17:27:42,259-selenium.webdriver.remote.remote_connection-INFO-Could not get IP address for host: 127.0.0.1
2019-03-06 17:27:42,259-selenium.webdriver.remote.remote_connection-INFO-Could not get IP address for host: 127.0.0.1
2019-03-06 17:27:43,263-urllib3.connectionpool-WARNING-Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019B524ECF28>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2019-03-06 17:27:43,263-urllib3.connectionpool-WARNING-Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019B524ECF28>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2019-03-06 17:27:44,265-urllib3.connectionpool-WARNING-Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019B5250F0B8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2019-03-06 17:27:44,265-urllib3.connectionpool-WARNING-Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019B5250F0B8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2019-03-06 17:27:45,268-urllib3.connectionpool-WARNING-Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019B5250F160>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2019-03-06 17:27:45,268-urllib3.connectionpool-WARNING-Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019B5250F160>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',)': /wd/hub/session
2019-03-06 17:27:53,884-urllib3.poolmanager-INFO-Redirecting http://127.0.0.1:4723/wd/hub/session -> http://127.0.0.1:4723/wd/hub/session/acc78169-ddae-4711-93cc-c84ac5d023f7
2019-03-06 17:27:53,884-urllib3.poolmanager-INFO-Redirecting http://127.0.0.1:4723/wd/hub/session -> http://127.0.0.1:4723/wd/hub/session/acc78169-ddae-4711-93cc-c84ac5d023f7
2019-03-06 17:28:02,155-root-INFO-现在关闭浏览器
2019-03-06 17:28:02,155-root-INFO-现在关闭浏览器
